### PR TITLE
introduce typographing

### PR DESCRIPTION
**Pull request by iamstarkov**
here is instruction how to test it

```
git clone git@github.com:iamstarkov/iamstarkov.github.io.git
cd iamstarkov.github.io
git checkout feat/typographic
cd node_modules/mdsat-textr
npm install
npm run tranpile
cd ../..
npm start
```

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
And how it is?

**Comment by iamstarkov** [comment]
its working
screen shot 2015-11-30 at 14 44 56

**Comment by denysdovhan** [comment]
＼（○＾ω＾○）／

**Comment by shuvalov-anton** [comment]
Awesome!

**Comment by iamstarkov** [comment]
markdown is ruining or fairy tale https://github.com/denysdovhan/mdast-textr/issues/4

**Comment by denysdovhan** [comment]
hey ho https://github.com/denysdovhan/denysdovhan.github.io/pull/6

**Pull request closed without merging**
