### PR TITLE
Port to Antwar

### PR DESCRIPTION
**Pull request by bebraw**
I don't expect you to accept this PR as is. This is just a quick port to show you how the blog might look like in Antwar. The port isn't complete (ie. gauges plugin is missing and meta) but those missing parts aren't hard to implement if needed.

### CODE REVIEW

**Comment by iamstarkov** [comment]
thanks a lot, will check it out today =)

**Comment by iamstarkov** [comment]
thanks for you effort, it looks good, require more work. For now will stay with gulp

**Comment by iamstarkov** [comment]
thanks for you effort, it looks good, require more work. For now will stay with gulp

**Comment by bebraw** [comment]
Ok, cool. Please open issues for possible missing bits.

I've been improving Antwar steadily. There's nicer highlighting and so on but of course it has been driven by my requirements.

**Pull request closed without merging**
